// How to run:
// export OPENAI_API_KEY=sk-yourkey
// ts-node generate-k6-test-ai.ts graphql-output.json
import * as fs from "fs";
import OpenAI from "openai";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const inputFile = process.argv[2];
const outputFile = process.argv[3] || "k6-test.js";

if (!inputFile) {
  console.error("Usage: ts-node generate-k6-test-openai.ts <inputJson> [outputFile]");
  process.exit(1);
}

const data = JSON.parse(fs.readFileSync(inputFile, "utf8"));
const { request, response } = data;

async function getSmartAssertions(sample: any, dataRoot: string) {
  const prompt = `
You are generating JavaScript code for k6 test assertions ONLY.

Context: We already have a variable 'r' containing the parsed response: r.data.${dataRoot}

Given this sample response structure:
${JSON.stringify(sample, null, 2)}

Generate ONLY these 2 things:
1. ONE destructuring line: const { field1, field2, ... } = r.data.${dataRoot};
2. ONE check() call with assertions inside it

Rules:
- Do NOT include the sample data
- Do NOT include any variable declarations like const r = {...}
- Do NOT include imports or requires
- Start with the destructuring line
- Then the check() call
- Include smart business-logic assertions (IDs match, non-empty fields, positive numbers, valid types)
- Use clear assertion names

Return ONLY those 2 code blocks, NO markdown fences, NO explanations, NO extra code.
`;

  const completion = await openai.responses.create({
    model: "gpt-4.1-mini",
    input: prompt,
  });

  let code = completion.output_text.trim();

  // Remove code fences if model returned them
  code = code.replace(/```(javascript|js)?/g, "").replace(/```/g, "").trim();
  
  // Remove any require/import statements
  code = code.replace(/^.*require\(.*\);?$/gm, "").trim();
  code = code.replace(/^.*import\s+.*$/gm, "").trim();
  
  // Remove any variable declarations that create the mock response
  code = code.replace(/^const r = \{[\s\S]*?\};?$/gm, "").trim();

  return code;
}

async function main() {
  const dataRoot = Object.keys(response.data || {})[0];
  const sample = response.data[dataRoot];

  const aiCode = await getSmartAssertions(sample, dataRoot);
  const queryString = request.query.replace(/`/g, "\\`");

  const k6Script = `import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = { vus: 1, duration: '5s' };

export default function () {
  const url = '${request.url}';
  const payload = JSON.stringify({
    query: \`${queryString}\`,
    operationName: '${request.operationName}',
    variables: ${JSON.stringify(request.variables, null, 2)}
  });
  const headers = { 'Content-Type': 'application/json' };
  const res = http.post(url, payload, { headers });

  check(res, { 'status is 200': (r) => r.status === 200 });

  const json = res.json();
  const r = json;

  // --- Smart assertions generated by OpenAI ---
${aiCode
  .split("\n")
  .map(line => "  " + line)
  .join("\n")}

  sleep(1);
}
`;

  fs.writeFileSync(outputFile, k6Script);
  console.log(`✅ k6 test with AI-generated, compilable assertions written to ${outputFile}`);
}

main().catch(err => console.error(err));
